##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##
blox:
  world:
    pose: [1.5, 0.080, 1.55, 0.043, -0.471, 0.284, 0.834]
    map_path: "scene/nvblox/srl_ur10_bins.nvblx"
    mesh_file_path: "scene/nvblox/srl_ur10_bins.obj"
    integrator_type: "tsdf"
    voxel_size: 0.03

  
